import { escapeNixString } from '@euvlok/shared';
import type { BrowserType, ExtensionResult } from './types';

export function generateNixFile(
  results: ExtensionResult[],
  conditional: boolean,
  browser: BrowserType,
) {
  const plain = results
    .filter((r) => !r.extension.condition && r.nixEntry)
    .sort((a, b) => a.extension.id.localeCompare(b.extension.id));

  const gated = results
    .filter((r) => r.extension.condition && r.nixEntry)
    .sort((a, b) => a.extension.id.localeCompare(b.extension.id));

  const lines: string[] = [
    '# This file is auto-generated by an update script',
    '# DO NOT edit manually',
  ];

  if (browser === 'chromium') {
    lines.push('{', '  pkgs,');
    if (conditional) lines.push('  config,');
    lines.push('  lib,', '  ...', '}:', 'lib.flatten [');
    plain.map((e) => lines.push(e.nixEntry!));
    gated.map((e) => {
      lines.push(`  (lib.optionals (${escapeNixString(e.extension.condition!)}) [`);
      lines.push(e.nixEntry!);
      lines.push('  ])');
    });
    lines.push(']');
    return lines.join('\n') + '\n';
  }

  lines.push('{ buildFirefoxXpiAddon, fetchurl, lib, stdenv }:', '  {');
  plain.map((e) => lines.push(`    "${e.extension.id}" = buildFirefoxXpiAddon ${e.nixEntry!};`));
  gated.map((e) => {
    lines.push(
      `    (lib.optionals (${escapeNixString(e.extension.condition!)}) [\n      buildFirefoxXpiAddon ${e.nixEntry!}\n    ]);`,
    );
  });
  lines.push('  }');
  return lines.join('\n') + '\n';
}
