import { escapeNixString } from '@euvlok/core';
import type { BrowserType, ExtensionResult } from './types';

type GeneratedExtensionResult = ExtensionResult & { nixEntry: string };
type GatedExtensionResult = GeneratedExtensionResult & {
  extension: GeneratedExtensionResult['extension'] & { condition: string };
};

function hasNixEntry(result: ExtensionResult): result is GeneratedExtensionResult {
  return !!result.nixEntry;
}

function isPlain(result: ExtensionResult): result is GeneratedExtensionResult {
  return !result.extension.condition && hasNixEntry(result);
}

function isGated(result: ExtensionResult): result is GatedExtensionResult {
  return !!result.extension.condition && hasNixEntry(result);
}

export function generateExtensionsNixFile(results: ExtensionResult[], conditional: boolean, browser: BrowserType) {
  const plain = results.filter(isPlain).sort((a, b) => a.extension.id.localeCompare(b.extension.id));

  const gated = results.filter(isGated).sort((a, b) => a.extension.id.localeCompare(b.extension.id));

  const lines: string[] = ['# This file is auto-generated by an update script', '# DO NOT edit manually'];

  if (browser === 'chromium') {
    lines.push('{', '  pkgs,');
    if (conditional) lines.push('  config,');
    lines.push('  lib,', '  ...', '}:', 'lib.lists.flatten [');
    plain.forEach((e) => {
      lines.push(e.nixEntry);
    });
    gated.forEach((e) => {
      lines.push(`  (lib.lists.optionals (${escapeNixString(e.extension.condition)}) [`);
      lines.push(e.nixEntry);
      lines.push('  ])');
    });
    lines.push(']');
    return `${lines.join('\n')}\n`;
  }

  lines.push('{ buildFirefoxXpiAddon, fetchurl, lib, stdenv }:', '  {');
  plain.forEach((e) => {
    lines.push(`    "${e.extension.id}" = buildFirefoxXpiAddon ${e.nixEntry};`);
  });
  gated.forEach((e) => {
    lines.push(
      `    (lib.lists.optionals (${escapeNixString(e.extension.condition)}) [\n      buildFirefoxXpiAddon ${e.nixEntry}\n    ]);`,
    );
  });
  lines.push('  }');
  return `${lines.join('\n')}\n`;
}
