#!/usr/bin/env sh
exec zig run -lc \
  --dep chezmoi \
  -Mroot="$CHEZMOI_SOURCE_DIR/.chezmoiscripts/run_onchange_after_zsh_bash_init.zig" \
  -Mchezmoi="$CHEZMOI_SOURCE_DIR/../../lib/zig/chezmoi/script.zig" \
  -- "$@"
