version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/build-nix-flake-target"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "nix"
    ignore:
      - dependency-name: "catppuccin-gtk"
