keys:
  - &ashuramaruzxc_unsigned-int64 age1a4cshc8aq9v9ez57r4mljddls3wfzchpc2uhmvjvnzk4wvr2mdequaej6d # @ashuramaruzxc server
  - &ashuramaruzxc_shared age1lt87d4wz67kng3enp0wx4yqwr47pe5xrqatggmhxucyed6rkh4hqphyk56 # @ashuramaruzxc home machine
creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *ashuramaruzxc_unsigned-int64
          - *ashuramaruzxc_shared
