inherits = "catppuccin_frappe"

"string.special" = "pink"
"variable.other.member" = "pink"
"keyword" = "pink"
"keyword.control.conditional" = { fg = "pink", modifiers = ["italic"] }
"function" = "pink"
"function.macro" = "pink"
"tag" = "pink"
"special" = "pink"

"markup.heading.1" = "pink"
"markup.heading.2" = "pink"
"markup.heading.3" = "pink"
"markup.heading.4" = "pink"
"markup.heading.5" = "pink"
"markup.heading.6" = "pink"
"markup.list" = "pink"
"markup.link.url" = { fg = "pink", modifiers = ["italic", "underlined"] }
"markup.link.text" = "pink"
"markup.link.label" = "pink"
"diff.delta" = "pink"

"ui.linenr.selected" = { fg = "pink" }
"ui.statusline.normal" = { fg = "base", bg = "pink", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base", bg = "pink", modifiers = ["bold"] }
"ui.bufferline.active" = { fg = "pink", bg = "base", underline = { color = "pink", style = "line" } }
"ui.text.directory" = { fg = "pink" }
"ui.virtual.jump-label" = { fg = "pink", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "base", bg = "pink" }
"ui.cursor.primary.normal" = { fg = "base", bg = "pink" }
"ui.cursor.primary.select" = { fg = "base", bg = "pink" }
