# This file is auto-generated by an update script
# DO NOT edit manually
{
  buildFirefoxXpiAddon,
  fetchurl,
  lib,
  stdenv,
}:
{
  "clearurls" = buildFirefoxXpiAddon {
    name = "clearurls";
    version = "1.27.3";
    addonId = "clearurls";
    url = "https://addons.mozilla.org/firefox/downloads/file/4432106/clearurls-1.27.3.xpi";
    sha256 = "sha256-VJJrbkJ01ZNaX8DapjIPHTcePS8aWHdGfKOrIqZcTyA=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "magnolia@12.34" = buildFirefoxXpiAddon {
    name = "magnolia@12.34";
    version = "4.2.9.6";
    addonId = "magnolia@12.34";
    url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-latest.xpi&inline=false&commit=5b8b5ddb964fdf20dbe856b1789acb17838b8ed7";
    sha256 = "sha256-Jf9wYjFVxEfAGXo7qMFG28gW4pipvNuOAvqJGXKBq4s=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "refined-github-" = buildFirefoxXpiAddon {
    name = "refined-github-";
    version = "26.2.2";
    addonId = "refined-github-";
    url = "https://addons.mozilla.org/firefox/downloads/file/4682198/refined_github-26.2.2.xpi";
    sha256 = "sha256-Ag8ECpc7cA26yfrmYRrRtRargNRuMOKWt0qB4PFL2fQ=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "sponsorblock" = buildFirefoxXpiAddon {
    name = "sponsorblock";
    version = "6.1.2";
    addonId = "sponsorblock";
    url = "https://addons.mozilla.org/firefox/downloads/file/4644570/sponsorblock-6.1.2.xpi";
    sha256 = "sha256-WY9myetrurK9X4c3a2MqWGD0QtNpTiM2EPWzf4tuPxA=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "ublock-origin" = buildFirefoxXpiAddon {
    name = "ublock-origin";
    version = "1.69.0";
    addonId = "ublock-origin";
    url = "https://addons.mozilla.org/firefox/downloads/file/4675310/ublock_origin-1.69.0.xpi";
    sha256 = "sha256-eFvN5ool+qiglJlk7F/+m9y4XT8K4hwj9gfGyPkUcs8=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "violentmonkey" = buildFirefoxXpiAddon {
    name = "violentmonkey";
    version = "2.34.0";
    addonId = "violentmonkey";
    url = "https://addons.mozilla.org/firefox/downloads/file/4677263/violentmonkey-2.34.0.xpi";
    sha256 = "sha256-rFjrJ5Z2Xac9tXGpSRNSrLuCh7dszZ4jdWEjZKTNVHM=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
}
