# This file is auto-generated by an update script
# DO NOT edit manually
{
  buildFirefoxXpiAddon,
  fetchurl,
  lib,
  stdenv,
}:
{
  "angular-devtools" = buildFirefoxXpiAddon {
    pname = "angular-devtools";
    version = "1.9.0";
    addonId = "{20a9bb38-ed7c-4faf-9aaf-7c5d241fd747}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4677798/angular_devtools-1.9.0.xpi";
    sha256 = "sha256-qZ6jSPkMhARpdjhpDPfrpQiH3oGsei3xF0w//3+EXpg=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "activeTab"
        "storage"
        "http://*/*"
        "https://*/*"
        "file:///*"
      ];
    };
  };
  "bitwarden-password-manager" = buildFirefoxXpiAddon {
    pname = "bitwarden-password-manager";
    version = "2026.2.0";
    addonId = "{446900e4-71c2-419f-a6a7-df9c091e268b}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4715321/bitwarden_password_manager-2026.2.0.xpi";
    sha256 = "sha256-5UmZ1FrhzQAUUqNClCQGM8iala6DLyEnIddGqJVVlY4=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "*://*/*"
        "alarms"
        "clipboardRead"
        "clipboardWrite"
        "contextMenus"
        "idle"
        "storage"
        "tabs"
        "unlimitedStorage"
        "webNavigation"
        "webRequest"
        "webRequestBlocking"
        "notifications"
      ];
    };
  };
  "darkreader" = buildFirefoxXpiAddon {
    pname = "darkreader";
    version = "4.9.123";
    addonId = "addon@darkreader.org";
    url = "https://addons.mozilla.org/firefox/downloads/file/4710145/darkreader-4.9.123.xpi";
    sha256 = "sha256-mj5s2sU/ICV72BJkUywWr+2tAOsmI73tie0rMLHkAkM=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "tabs"
        "theme"
        "<all_urls>"
      ];
    };
  };
  "facebook-container" = buildFirefoxXpiAddon {
    pname = "facebook-container";
    version = "2.3.12";
    addonId = "@contain-facebook";
    url = "https://addons.mozilla.org/firefox/downloads/file/4451874/facebook_container-2.3.12.xpi";
    sha256 = "sha256-M2m9hlh3hg5tfTg5nVkCswDT1XN6yy0TQv9b6x03gME=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "browsingData"
        "contextualIdentities"
        "cookies"
        "management"
        "storage"
        "tabs"
        "webRequestBlocking"
        "webRequest"
      ];
    };
  };
  "firefox-color" = buildFirefoxXpiAddon {
    pname = "firefox-color";
    version = "2.1.7";
    addonId = "FirefoxColor@mozilla.com";
    url = "https://addons.mozilla.org/firefox/downloads/file/3643624/firefox_color-2.1.7.xpi";
    sha256 = "sha256-t/sHtniPcjPdYiPngOGJtMe5VsJcQEk8KNcCBJMkkpI=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "theme"
        "storage"
        "tabs"
      ];
    };
  };
  "floccus" = buildFirefoxXpiAddon {
    pname = "floccus";
    version = "5.8.6";
    addonId = "floccus@handmadeideas.org";
    url = "https://addons.mozilla.org/firefox/downloads/file/4673195/floccus-5.8.6.xpi";
    sha256 = "sha256-UqczO5pJhN9l0K1LDE0myDL/9JJbPEKKmU9rF76gPPM=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "*://*/*"
        "alarms"
        "bookmarks"
        "storage"
        "unlimitedStorage"
        "tabs"
        "tabGroups"
        "identity"
      ];
    };
  };
  "foxyproxy-standard" = buildFirefoxXpiAddon {
    pname = "foxyproxy-standard";
    version = "9.2";
    addonId = "foxyproxy@eric.h.jung";
    url = "https://addons.mozilla.org/firefox/downloads/file/4472757/foxyproxy_standard-9.2.xpi";
    sha256 = "sha256-jbHGR5mmD3Eh1Rpun2sEGHFZg0SSfJWv6DDCeIDwiF0=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "contextMenus"
        "downloads"
        "notifications"
        "proxy"
        "storage"
        "tabs"
        "webRequest"
        "webRequestAuthProvider"
        "<all_urls>"
      ];
    };
  };
  "multi-account-containers" = buildFirefoxXpiAddon {
    pname = "multi-account-containers";
    version = "8.3.7";
    addonId = "@testpilot-containers";
    url = "https://addons.mozilla.org/firefox/downloads/file/4733069/multi_account_containers-8.3.7.xpi";
    sha256 = "sha256-f29e97EG0z0bmdLF5TogZdB/eEsYUv6bn3g5TptAUWU=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "activeTab"
        "cookies"
        "contextMenus"
        "contextualIdentities"
        "history"
        "idle"
        "management"
        "storage"
        "unlimitedStorage"
        "tabs"
        "webRequestBlocking"
        "webRequest"
      ];
    };
  };
  "old-reddit-redirect" = buildFirefoxXpiAddon {
    pname = "old-reddit-redirect";
    version = "2.1.0";
    addonId = "{9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4716803/old_reddit_redirect-2.1.0.xpi";
    sha256 = "sha256-LRpDKsqxtd2N+4/X7trfiLXBk4YASYoAlxDt9O8bD5o=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "declarativeNetRequestWithHostAccess"
        "*://reddit.com/*"
        "*://www.reddit.com/*"
        "*://np.reddit.com/*"
        "*://amp.reddit.com/*"
        "*://i.reddit.com/*"
        "*://i.redd.it/*"
        "*://preview.redd.it/*"
      ];
    };
  };
  "react-devtools" = buildFirefoxXpiAddon {
    pname = "react-devtools";
    version = "6.1.1";
    addonId = "@react-devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4432990/react_devtools-6.1.1.xpi";
    sha256 = "sha256-staeIgQCvWuLx9gzlIkVsdbcq7RTodUIcqPbhg/ZLEY=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "scripting"
        "storage"
        "tabs"
        "clipboardWrite"
        "<all_urls>"
      ];
    };
  };
  "reddit-enhancement-suite" = buildFirefoxXpiAddon {
    pname = "reddit-enhancement-suite";
    version = "5.24.8";
    addonId = "jid1-xUfzOsOFlzSOXg@jetpack";
    url = "https://addons.mozilla.org/firefox/downloads/file/4424459/reddit_enhancement_suite-5.24.8.xpi";
    sha256 = "sha256-FYQFxQcEos0rxXwmipW0Hay6UJtw1x1uooCwQhW7h3M=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "https://*.reddit.com/*"
        "cookies"
        "identity"
        "tabs"
        "history"
        "storage"
        "scripting"
        "unlimitedStorage"
        "https://publish.twitter.com/oembed"
        "https://backend.deviantart.com/oembed"
        "https://api.gyazo.com/api/oembed"
        "https://api.tumblr.com/v2/blog/*/posts"
        "https://xkcd.com/*/info.0.json"
        "https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/*"
        "https://www.googleapis.com/drive/v3/*"
        "https://*.redd.it/*"
        "https://www.flickr.com/services/oembed"
        "https://embed.bsky.app/oembed"
      ];
    };
  };
  "reduxdevtools" = buildFirefoxXpiAddon {
    pname = "reduxdevtools";
    version = "3.2.10";
    addonId = "extension@redux.devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4467343/reduxdevtools-3.2.10.xpi";
    sha256 = "sha256-7ysQoryLDRqETRRuPur/QH6qpjzQVk246v2HDIeoiVY=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "notifications"
        "contextMenus"
        "tabs"
        "storage"
        "file:///*"
        "http://*/*"
        "https://*/*"
      ];
    };
  };
  "search_by_image" = buildFirefoxXpiAddon {
    pname = "search_by_image";
    version = "8.5.0";
    addonId = "{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4689098/search_by_image-8.5.0.xpi";
    sha256 = "sha256-NwlAp3/zxTmKMAwQJJ7PThOXVohHMoKvuaJhOma+L7M=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "unlimitedStorage"
        "tabs"
        "activeTab"
        "notifications"
        "webRequest"
        "webRequestBlocking"
        "<all_urls>"
        "scripting"
      ];
    };
  };
  "steam-database" = buildFirefoxXpiAddon {
    pname = "steam-database";
    version = "4.33";
    addonId = "firefox-extension@steamdb.info";
    url = "https://addons.mozilla.org/firefox/downloads/file/4704123/steam_database-4.33.xpi";
    sha256 = "sha256-enoGkukwbsG06vIbtKy68NCx9qbprNykCQPfA/2R908=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "https://steamdb.info/*"
        "https://steamcommunity.com/*"
        "https://*.steampowered.com/*"
      ];
    };
  };
  "styl-us" = buildFirefoxXpiAddon {
    pname = "styl-us";
    version = "2.3.19";
    addonId = "{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4661054/styl_us-2.3.19_qtD9vir.xpi";
    sha256 = "sha256-/tl9m4y4eT0bH5XJWr+vdmA3fAunHUnsSP/T1nb2avE=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "tabs"
        "unlimitedStorage"
        "webNavigation"
        "webRequest"
        "webRequestBlocking"
        "<all_urls>"
      ];
    };
  };
  "tabliss" = buildFirefoxXpiAddon {
    pname = "tabliss";
    version = "2.6.0";
    addonId = "extension@tabliss.io";
    url = "https://addons.mozilla.org/firefox/downloads/file/3940751/tabliss-2.6.0.xpi";
    sha256 = "sha256-3nZoEPI0scE//bcEeubL8G7XnD0ItRoH5HZvrf8InA8=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
      ];
    };
  };
  "translate-web-pages" = buildFirefoxXpiAddon {
    pname = "translate-web-pages";
    version = "7.5";
    addonId = "{d3a88b28-681e-43b6-ac3d-22f92ba18818}";
    url = "https://addons.mozilla.org/firefox/downloads/file/3656490/translate_web_pages-7.5.xpi";
    sha256 = "sha256-ENWrAcTpe9zxIoYlRYoF/kVHtZ1upBjeDuZHy3Gn6Nk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
        "storage"
        "activeTab"
        "contextMenus"
      ];
    };
  };
  "user-agent-string-switcher" = buildFirefoxXpiAddon {
    pname = "user-agent-string-switcher";
    version = "0.6.6";
    addonId = "{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4593736/user_agent_string_switcher-0.6.6.xpi";
    sha256 = "sha256-nB/uKb2JpyH3r412qZeqytAn1PKxQc2wQ+6QJ7iWdZk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "contextMenus"
        "scripting"
        "declarativeNetRequestWithHostAccess"
        "<all_urls>"
      ];
    };
  };
  "view-page-archive" = buildFirefoxXpiAddon {
    pname = "view-page-archive";
    version = "7.3.0";
    addonId = "{d07ccf11-c0cd-4938-a265-2a4d6ad01189}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4695473/view_page_archive-7.3.0.xpi";
    sha256 = "sha256-28rxrQLBZOikRly9wBNofBa236gPxCsEoul+nzwARHo=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "alarms"
        "contextMenus"
        "storage"
        "unlimitedStorage"
        "tabs"
        "activeTab"
        "notifications"
        "webRequest"
        "webRequestBlocking"
        "<all_urls>"
      ];
    };
  };
  "vue-js-devtools" = buildFirefoxXpiAddon {
    pname = "vue-js-devtools";
    version = "7.7.7";
    addonId = "{5caff8cc-3d2e-4110-a88a-003cc85b3858}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4508409/vue_js_devtools-7.7.7.xpi";
    sha256 = "sha256-VnLNDTKY+lfy9R5GRAEeQVLm4pH28zhgFJXdgDczEWk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "<all_urls>"
      ];
    };
  };
  "youtube-no-translation" = buildFirefoxXpiAddon {
    pname = "youtube-no-translation";
    version = "2.21.4";
    addonId = "{9a3104a2-02c2-464c-b069-82344e5ed4ec}";
    url = "https://addons.mozilla.org/firefox/downloads/file/4732610/youtube_no_translation-2.21.4.xpi";
    sha256 = "sha256-ksl7a+odHRRWPEZ6KZPNRIIoq6iVoW3xaIfGUGkHLpk=";
    meta = with lib; {
      platforms = platforms.all;
      mozPermissions = [
        "storage"
        "*://*.youtube.com/*"
        "*://*.youtube-nocookie.com/*"
      ];
    };
  };
}
