# This file is auto-generated by an update script
# DO NOT edit manually
{
  buildFirefoxXpiAddon,
  fetchurl,
  lib,
  stdenv,
}:
{
  "angular-devtools" = buildFirefoxXpiAddon {
    name = "angular-devtools";
    version = "1.9.0";
    addonId = "angular-devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4677798/angular_devtools-1.9.0.xpi";
    sha256 = "sha256-qZ6jSPkMhARpdjhpDPfrpQiH3oGsei3xF0w//3+EXpg=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "bitwarden-password-manager" = buildFirefoxXpiAddon {
    name = "bitwarden-password-manager";
    version = "2025.12.1";
    addonId = "bitwarden-password-manager";
    url = "https://addons.mozilla.org/firefox/downloads/file/4664623/bitwarden_password_manager-2025.12.1.xpi";
    sha256 = "sha256-p6Ej7uTkD92K98DGckNzHdzDeuFJjPKCiZX0kFYAxR8=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "darkreader" = buildFirefoxXpiAddon {
    name = "darkreader";
    version = "4.9.119";
    addonId = "darkreader";
    url = "https://addons.mozilla.org/firefox/downloads/file/4665768/darkreader-4.9.119.xpi";
    sha256 = "sha256-JhpCLy/Pg+4yCseigJ2Sa4Y3+63s6KV1i4Jb0GApRL4=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "facebook-container" = buildFirefoxXpiAddon {
    name = "facebook-container";
    version = "2.3.12";
    addonId = "facebook-container";
    url = "https://addons.mozilla.org/firefox/downloads/file/4451874/facebook_container-2.3.12.xpi";
    sha256 = "sha256-M2m9hlh3hg5tfTg5nVkCswDT1XN6yy0TQv9b6x03gME=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "firefox-color" = buildFirefoxXpiAddon {
    name = "firefox-color";
    version = "2.1.7";
    addonId = "firefox-color";
    url = "https://addons.mozilla.org/firefox/downloads/file/3643624/firefox_color-2.1.7.xpi";
    sha256 = "sha256-t/sHtniPcjPdYiPngOGJtMe5VsJcQEk8KNcCBJMkkpI=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "floccus" = buildFirefoxXpiAddon {
    name = "floccus";
    version = "5.8.6";
    addonId = "floccus";
    url = "https://addons.mozilla.org/firefox/downloads/file/4673195/floccus-5.8.6.xpi";
    sha256 = "sha256-UqczO5pJhN9l0K1LDE0myDL/9JJbPEKKmU9rF76gPPM=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "foxyproxy-standard" = buildFirefoxXpiAddon {
    name = "foxyproxy-standard";
    version = "9.2";
    addonId = "foxyproxy-standard";
    url = "https://addons.mozilla.org/firefox/downloads/file/4472757/foxyproxy_standard-9.2.xpi";
    sha256 = "sha256-jbHGR5mmD3Eh1Rpun2sEGHFZg0SSfJWv6DDCeIDwiF0=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "magnolia@12.34" = buildFirefoxXpiAddon {
    name = "magnolia@12.34";
    version = "4.2.9.6";
    addonId = "magnolia@12.34";
    url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-latest.xpi&inline=false&commit=5b8b5ddb964fdf20dbe856b1789acb17838b8ed7";
    sha256 = "sha256-Jf9wYjFVxEfAGXo7qMFG28gW4pipvNuOAvqJGXKBq4s=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "multi-account-containers" = buildFirefoxXpiAddon {
    name = "multi-account-containers";
    version = "8.3.6";
    addonId = "multi-account-containers";
    url = "https://addons.mozilla.org/firefox/downloads/file/4627302/multi_account_containers-8.3.6.xpi";
    sha256 = "sha256-vz3jW4RL7PFmRJ8dkn+ZSiq6+4/Ezod+ynqMbNEk00o=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "old-reddit-redirect" = buildFirefoxXpiAddon {
    name = "old-reddit-redirect";
    version = "2.0.9";
    addonId = "old-reddit-redirect";
    url = "https://addons.mozilla.org/firefox/downloads/file/4526031/old_reddit_redirect-2.0.9.xpi";
    sha256 = "sha256-kedVS4W3kgH3LBdfbl9vSTszMO6DO4KJ+2QX2ZGt1Qo=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "react-devtools" = buildFirefoxXpiAddon {
    name = "react-devtools";
    version = "6.1.1";
    addonId = "react-devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4432990/react_devtools-6.1.1.xpi";
    sha256 = "sha256-staeIgQCvWuLx9gzlIkVsdbcq7RTodUIcqPbhg/ZLEY=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "reddit-enhancement-suite" = buildFirefoxXpiAddon {
    name = "reddit-enhancement-suite";
    version = "5.24.8";
    addonId = "reddit-enhancement-suite";
    url = "https://addons.mozilla.org/firefox/downloads/file/4424459/reddit_enhancement_suite-5.24.8.xpi";
    sha256 = "sha256-FYQFxQcEos0rxXwmipW0Hay6UJtw1x1uooCwQhW7h3M=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "reduxdevtools" = buildFirefoxXpiAddon {
    name = "reduxdevtools";
    version = "3.2.10";
    addonId = "reduxdevtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4467343/reduxdevtools-3.2.10.xpi";
    sha256 = "sha256-7ysQoryLDRqETRRuPur/QH6qpjzQVk246v2HDIeoiVY=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "search-by-image" = buildFirefoxXpiAddon {
    name = "search-by-image";
    version = "1.3";
    addonId = "search-by-image";
    url = "https://addons.mozilla.org/firefox/downloads/file/3786018/search_by_image-1.3.xpi";
    sha256 = "sha256-zXAOAKxOGbYP979IKVOAgrOjpor/Ct5qnx7Dzcs8M9I=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "steam-database" = buildFirefoxXpiAddon {
    name = "steam-database";
    version = "4.32";
    addonId = "steam-database";
    url = "https://addons.mozilla.org/firefox/downloads/file/4657779/steam_database-4.32.xpi";
    sha256 = "sha256-ibK4EuD0tY00qvLtj6mhhoQtbJ3wY2Q3+Ur/TS4JgEw=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "stylus" = buildFirefoxXpiAddon {
    name = "stylus";
    version = "2.0";
    addonId = "stylus";
    url = "https://addons.mozilla.org/firefox/downloads/file/2415216/stylus-2.0.xpi";
    sha256 = "sha256-0f1TXaJ9/jY1plToRQprBdiD+mwsvtvrL0iKA0xDE7U=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "tabliss" = buildFirefoxXpiAddon {
    name = "tabliss";
    version = "2.6.0";
    addonId = "tabliss";
    url = "https://addons.mozilla.org/firefox/downloads/file/3940751/tabliss-2.6.0.xpi";
    sha256 = "sha256-3nZoEPI0scE//bcEeubL8G7XnD0ItRoH5HZvrf8InA8=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "translate-web-pages" = buildFirefoxXpiAddon {
    name = "translate-web-pages";
    version = "7.5";
    addonId = "translate-web-pages";
    url = "https://addons.mozilla.org/firefox/downloads/file/3656490/translate_web_pages-7.5.xpi";
    sha256 = "sha256-ENWrAcTpe9zxIoYlRYoF/kVHtZ1upBjeDuZHy3Gn6Nk=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "user-agent-string-switcher" = buildFirefoxXpiAddon {
    name = "user-agent-string-switcher";
    version = "0.6.6";
    addonId = "user-agent-string-switcher";
    url = "https://addons.mozilla.org/firefox/downloads/file/4593736/user_agent_string_switcher-0.6.6.xpi";
    sha256 = "sha256-nB/uKb2JpyH3r412qZeqytAn1PKxQc2wQ+6QJ7iWdZk=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "view-page-archive" = buildFirefoxXpiAddon {
    name = "view-page-archive";
    version = "7.2.0";
    addonId = "view-page-archive";
    url = "https://addons.mozilla.org/firefox/downloads/file/4635665/view_page_archive-7.2.0.xpi";
    sha256 = "sha256-4jTX0ihjiBs2dvVoUwZgJEO+pDLCCvdhlZRU8Wlud5s=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "vue-js-devtools" = buildFirefoxXpiAddon {
    name = "vue-js-devtools";
    version = "7.7.7";
    addonId = "vue-js-devtools";
    url = "https://addons.mozilla.org/firefox/downloads/file/4508409/vue_js_devtools-7.7.7.xpi";
    sha256 = "sha256-VnLNDTKY+lfy9R5GRAEeQVLm4pH28zhgFJXdgDczEWk=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
  "youtube-no-translation" = buildFirefoxXpiAddon {
    name = "youtube-no-translation";
    version = "2.20.0";
    addonId = "youtube-no-translation";
    url = "https://addons.mozilla.org/firefox/downloads/file/4633946/youtube_no_translation-2.20.0.xpi";
    sha256 = "sha256-KY8CRp2GBrlPLl/S4jBU6XOeoW9WxqhRDO/CCd6VNxw=";
    meta = with lib; {
      platforms = platforms.all;
    };
  };
}
