# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.lists.flatten [
  {
    id = "bhchdcejhohfmigjafbampogmaanbfkg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H8jZlVeKkCfdnAMuLnDtp_L4hHAeJfAzU90JOwizHwZGT8c58hc0fpfsMNpDRA74eVGofvkmLGOxpeGoAsIyXaBiOlkhd53DwW-ukaXxiwDVVUaXWKEviMC9SmBS8YAxlKa5fj2nRrQRai5C_OK6nT4gKFU2Svq/BHCHDCEJHOHFMIGJAFBAMPOGMAANBFKG_0_6_7_0.crx";
      name = "bhchdcejhohfmigjafbampogmaanbfkg.crx";
      hash = "sha256-oKSxB1tJLYHWOEvRFq9+apmWkQ+dZGsng31q/RNoUIg=";
    };
    version = "0.6.7";
  }
  {
    id = "cdglnehniifkbagbbombnjghhcihifij";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H_nO4q4N0r4xeFbOoZUK1JLzpQMIwVivfJNMRfJJvY5XS0CbhRMG2SCW-STrMfb1oZOZxeDr0K7tvuwr6L7TUVEcBxbym0gWrxY9S5PuWF0MoZ98QDuJUTP3lPif78AxlKa5dcLJ5Qg3JLOkmy6M_nCyg915M4-/CDGLNEHNIIFKBAGBBOMBNJGHHCIHIFIJ_1_2_2_5.crx";
      name = "cdglnehniifkbagbbombnjghhcihifij.crx";
      hash = "sha256-weiUUUiZeeIlz/k/d9VDSKNwcQtmAahwSIHt7Frwh7E=";
    };
    version = "1.2.2.5";
  }
  {
    id = "clngdbkpkpeebahjckkjfobafhncgmne";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9aIyApQcLAk4_hVxgtlXiyiC2Fxb7IgaoeluL7oWEFyYNcLYzJPvx74l_5tSOt4ck6xE7Q1zC6ZjgpGeDND4vHqdPKv-7xCGdNsI7XfczTHTgRT0tBPkaL0cTAdIcAxlKa5XXMb_ad55Pr-3yvb8meCkQ30mEZ/CLNGDBKPKPEEBAHJCKKJFOBAFHNCGMNE_2_4_5_0.crx";
      name = "clngdbkpkpeebahjckkjfobafhncgmne.crx";
      hash = "sha256-mST2glhYqJuYce1SDxnqHdSIaVsGJ/m5CTcE8Tlib2E=";
    };
    version = "2.4.5";
  }
  {
    id = "cnojnbdhbhnkbcieeekonklommdnndci";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9HV3rnTcs-vQqPKBE8Jy8oPhlTHdmDne_UhWLxgCKCfkKlzhhklt_QJl2DTdEGipzsuwBt5Hwr_2x5a2i8Yc7l2a7J6XPhiJKEvTF-G7R1MU2hQAqFAb3j1s6GfpEAxlKa5WYspzuKjMMgKPAqL0qkHymiY7lr/CNOJNBDHBHNKBCIEEEKONKLOMMDNNDCI_8_5_4_0.crx";
      name = "cnojnbdhbhnkbcieeekonklommdnndci.crx";
      hash = "sha256-zp7xrEAQ544OZV98dP/aAxhsBQAsLKqfFAqzn9NRQSY=";
    };
    version = "8.5.4";
  }
  {
    id = "dneaehbmnbhcippjikoajpoabadpodje";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9LyIwrmEM3Dne8D2e8LZYCJLCHBSCjHURS5Vc7-x-LNJSgVCiSkgpvF2-NBzRzG0Ttu5GLo1AqO80Rh_NhM__IbF-T93m4po_Y6urqM00vX_KMJQ19jAz1zr1nKM4AxlKa5bq1YwG2MIFYYpyMrzWcviJlwZSo/DNEAEHBMNBHCIPPJIKOAJPOABADPODJE_2_2_0_0.crx";
      name = "dneaehbmnbhcippjikoajpoabadpodje.crx";
      hash = "sha256-yA/ZCQTBEduzZjrIFNd2x8fVVoc4W+MOPmu78gMPUm8=";
    };
    version = "2.2.0";
  }
  {
    id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9YtxdbklhtavhDLIp6EU8GdmXC3s7q0P0PsnAkubhNGm_yGgKNuLxRPYOpqUQXiTrGZ4gaqFx5ZZNytiwD4IqjQ4eX1gVnkI5BY-Ue8BckMsvs3B2Kf4bFoNOBZGwAxlKa5dIXbQ5C_UZngYeYTTw7KV6YfEFt/EIMADPBCBFNMBKOPOOJFEKHNKHDBIEEH_4_9_129_0.crx";
      name = "eimadpbcbfnmbkopoojfekhnkhdbieeh.crx";
      hash = "sha256-ncsb1tytQ4kt3AKP9l+YLfPtuhNammRF5PpxZx43qhM=";
    };
    version = "4.9.129";
  }
  {
    id = "fmkadmapgofadopljbjfkapdkoienihi";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9J1PgdK42IRIdAoSU_qaFya3QEi8bhVrAh6eOmmZXd9iWGyMgIDL-MKfQFd_OEvwfxvju60Ory0J0z6TivEiZaG6Mx7xS6ZzTvTOrvbDSfb54jiRZm8Ii_Lb29zTgAxlKa5aj5UfN8MoEnffa_f7ZgowVdpiDO/FMKADMAPGOFADOPLJBJFKAPDKOIENIHI_7_0_1_0.crx";
      name = "fmkadmapgofadopljbjfkapdkoienihi.crx";
      hash = "sha256-X3DIlm39NyFz8bGKVjubF8JGeS58EirqeETOBk8Hfgc=";
    };
    version = "7.0.1";
  }
  {
    id = "gcknhkkoolaabfmlnjonogaaifnjlfnp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9Ut_AXb59TFd8bOF5cMiweWwNduSS4WcE9HEOHSrkV9nd9rJV4B3_JzZ9ZbKP9qHSFglYWzai5zpq9wvtM1bfQbyQS_gI2XgPZ89xySYionIQXDaAJjYJ-G1ArhGsAxlKa5dR6ZDuMCxtg0wgKahg-G70SHJd6/GCKNHKKOOLAABFMLNJONOGAAIFNJLFNP_9_2_0_0.crx";
      name = "gcknhkkoolaabfmlnjonogaaifnjlfnp.crx";
      hash = "sha256-B0LnrmxNQ3B1iKk89jaIC6Q0k3IP3YEW6yJnW+n4sG4=";
    };
    version = "9.2";
  }
  {
    id = "hipekcciheckooncpjeljhnekcoolahp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H9Bu4021zN1B1jeTKJX5bqvwlgMEeoqKasfgrlDW-nwD4cTwCNVRkCmUBR-92Uzuo_0acQGDkJUh5u6pqDerWE1yb8GIQvOo3YtbHvuhz1qUHsiAMZSmuXvXOKMmxuh2zsZAfe-NFYyrKh2KQ/HIPEKCCIHECKOONCPJELJHNEKCOOLAHP_2_6_0_0.crx";
      name = "hipekcciheckooncpjeljhnekcoolahp.crx";
      hash = "sha256-3a3HVG6dWVRx+EQ48gohNlu3BOzVZrpoZCxnf3chzRY=";
    };
    version = "2.6.0";
  }
  {
    id = "hkgfoiooedgoejojocmhlaklaeopbecg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H-vOUPfE1wBSAVSpKRWoKYXpopT9ZF_xXzcia7ULIN5BSTuLSbcPtdac9qFwfpUIZccb5i99wIL1laniCp3v-QB3cG28Ot3LECsiVB1q21nfuPPfz_0ly3YZPJlqADGUprl0prz2K69mfRBywXwkMrEOmqsvGU/HKGFOIOOEDGOEJOJOCMHLAKLAEOPBECG_1_14_0_0.crx";
      name = "hkgfoiooedgoejojocmhlaklaeopbecg.crx";
      hash = "sha256-NaWNfAH9zyLIVpmK5+cb72PUZ3whU5NwCb+9BA45aGc=";
    };
    version = "1.14";
  }
  {
    id = "hkligngkgcpcolhcnkgccglchdafcnao";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H8vQxlVvGARE2t7outPY6EUUnyve_KTttw9IlqqySSexMkjMzasX8uKkNIVFilLcs2p9SRxsnQWtM2V7LAA2_ROlcdBpk-jIvizSO3cIsTovBfzb6F0BaOFQpbBrvoAxlKa5V5NLANaxRtghKXLWeFmBHKwsnIn/HKLIGNGKGCPCOLHCNKGCCGLCHDAFCNAO_7_3_3_0.crx";
      name = "hkligngkgcpcolhcnkgccglchdafcnao.crx";
      hash = "sha256-VeV7DBhFfRaZe/NVg4jadM0cR3CAskXMA7fnpKbQUmQ=";
    };
    version = "7.3.3";
  }
  {
    id = "ienfalfjdbdpebioblfackkekamfmbnh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H-a-4YG12-HDQHO882B5KXNNBAql9Cxw9XJnZ6XTD-A7pvT-T3Oookp6zUZ_P-wlD0wUG9NPMVo8DCFGeD_EAnSoFaQ-KUf0_ookF4urGf6D_1L45AutJAL2qo4Y1MAxlKa5WU90LpFAoYZcYex3kxx_Jqqc2SR/IENFALFJDBDPEBIOBLFACKKEKAMFMBNH_1_18_0_0.crx";
      name = "ienfalfjdbdpebioblfackkekamfmbnh.crx";
      hash = "sha256-2usTZBAjdnrQ+boN8ks+0H1OcgME2b67pR1AWWtGlgc=";
    };
    version = "1.18.0";
  }
  {
    id = "kbmfpngjjgdllneeigpgjifpgocmfgmb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H93P1GQA3Fn9fcuttsJysSOMd5qoJbpGvh7pAHclJQwNBp7AJ1Rld6eQvi6dt1kmQzQiZuteppcdqvbPb2lag5-hrcCv9vfwAVjnE4mmoAls8Ly2P9lvKLhB444WmImAMZSmuVGw-0ytovPV1OKnut_7K12IRksBw/KBMFPNGJJGDLLNEEIGPGJIFPGOCMFGMB_5_24_10_0.crx";
      name = "kbmfpngjjgdllneeigpgjifpgocmfgmb.crx";
      hash = "sha256-sGFL8CagNPKOPx8tXK/IPPuOSFwJiJe905gBnHb924k=";
    };
    version = "5.24.10";
  }
  {
    id = "kmcfjchnmmaeeagadbhoofajiopoceel";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H8POuVFFMKBfUJj7AGKOBnLU9zsAH7Kw3bBHuokiVpm5EAq-To0m-lJDLqzBPwW4DDAPbD_kKqXvClC1mSBxJ93VGakLmsh81dir9itMAbYxBEYODfDHh-Z6wn8UsEAxlKa5b66gmGevo3M8-EcjEh_vHBJRpU3/KMCFJCHNMMAEEAGADBHOOFAJIOPOCEEL_0_33_5_0.crx";
      name = "kmcfjchnmmaeeagadbhoofajiopoceel.crx";
      hash = "sha256-SaBM++yovHNqOUyurpcvsfotSUzHxgjc8GHvrLOOiGk=";
    };
    version = "0.33.5.0";
  }
  {
    id = "lmhkpmbekcpmknklioeibfkpmmfibljd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H-ZXhXuxqZFCbjUp3MpF0aFB0ukbqyvbRVu8bWvOsDGZZhyR9mdjyhtlkm8q1IJ-NKShTjPK2CM36DFSH219PRUm7--KvUWg8PDC9ydrusltFc9OBrKMc2UnQMvbXoAxlKa5cmFvEm2buNUgeR1C8IjqcbhjTzx/LMHKPMBEKCPMKNKLIOEIBFKPMMFIBLJD_3_2_10_0.crx";
      name = "lmhkpmbekcpmknklioeibfkpmmfibljd.crx";
      hash = "sha256-IjNQiQdZSwW8ZDNyUxJTuTBuhs9cpUjltOdwfzR4YKM=";
    };
    version = "3.2.10";
  }
  {
    id = "nhdogjmejiglipccpnnnanhbledajbpd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H99BrQbg8MXVdv-LlKvqtWyKA6D2Bxv7csQNr2UZJb-PoLNGeU2HOTQ8NBcZcLBXWtbax3yz6B7yO6qpmytep6Tc_5gmWXsAlX3XGzqOxRV7t7gLzfWi5wPK-Ikr3vZAMZSmuXOPKO1K8iJQzc3skflCt80byZDtw/NHDOGJMEJIGLIPCCPNNNANHBLEDAJBPD_7_7_7_0.crx";
      name = "nhdogjmejiglipccpnnnanhbledajbpd.crx";
      hash = "sha256-v1ZcI/2eLAdO1HFE0FBDNveH5fEFOI9zxihG3ukvASQ=";
    };
    version = "7.7.7";
  }
  {
    id = "nngceckbapebfimnlniiiahkandclblb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H_5IIKPKCTo6luRPoQog1QUSEn4OTriGfnBophN5DxJE4kMTZaClPMtVEpqmfCBIwJyTVHp9Y0ug82wHqSAkZVhr_YmMjW9qBrcC6Kr2cYpMrDE9IiBgbAyhRJvvn0aAMZSmuUN9detRDreGc88UECnTh_RMFEeOQ/NNGCECKBAPEBFIMNLNIIIAHKANDCLBLB_2026_7_0_0.crx";
      name = "nngceckbapebfimnlniiiahkandclblb.crx";
      hash = "sha256-PwXLkgGS9YjvBRUHgwiEtqiXkXmWngv3xA4Boqj9f74=";
    };
    version = "2026.7.0";
  }
  {
    id = "pobhoodpcipjmedfenaigbeloiidbflp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AUU14H8APFCSniReb5VhX22a4_vYt_nMiXZpDUl06EAlcazpPRzfveLE8aM_jS2VV75yKPBBgOPCfRT-1V69Ttln4IBimKibtSIeDU_wzio7_sIslVBm2R-hKZ1ZifvljdcAxlKa5c10LzEAyolZkrc7X5cmkdHpLyb_/POBHOODPCIPJMEDFENAIGBELOIIDBFLP_6_4_1_0.crx";
      name = "pobhoodpcipjmedfenaigbeloiidbflp.crx";
      hash = "sha256-4sMXmTnApAGaK2aEhgp+Cp1vPweS78wRDn9cuYU0+VU=";
    };
    version = "6.4.1";
  }
]
