# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "bhchdcejhohfmigjafbampogmaanbfkg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5-0isTFyXmpyi13W6NHJxLI7HrZfp1z4GbxUK065wWW8syRZqjXXUwgBtSuzaJ5nw8yb5sQHs7x3lQgdvMFPS16J0s7TElRiBPScuz76UVVWiQ7xWlheIhCkzT_78AxlKa5ZhrBtIqrDCjJFBx4KyMBWL3ppgf/BHCHDCEJHOHFMIGJAFBAMPOGMAANBFKG_0_6_6_0.crx";
      name = "bhchdcejhohfmigjafbampogmaanbfkg.crx";
      hash = "sha256-2n0HNRR2NRWTxO96ytORUedOiFAZmopmUHv/S43PB0k=";
    };
    version = "0.6.6";
  }
  {
    id = "cdglnehniifkbagbbombnjghhcihifij";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5kmXOQSNRNwhgFy4sqTFZPP6TlQRVw_LHGl-q7f-W7V97uvmWn7Rd-2J_WyUsNfW0AquNTSjPx0KUGucGj8BshNN-0Tu0GpbnxjfbvirJQOEmbt4jiQLwAFW2cyRkAxlKa5UICFOzqy_4hVyvgCQdsrsynOZUt/CDGLNEHNIIFKBAGBBOMBNJGHHCIHIFIJ_1_2_2_5.crx";
      name = "cdglnehniifkbagbbombnjghhcihifij.crx";
      hash = "sha256-weiUUUiZeeIlz/k/d9VDSKNwcQtmAahwSIHt7Frwh7E=";
    };
    version = "1.2.2.5";
  }
  {
    id = "clngdbkpkpeebahjckkjfobafhncgmne";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5SP-hi0gK-3Evk5gOM-voxvPq2-NGmalkwwNSJAIGfYhCXB_zhk5z94zd-NEmr4OBChqrunQRsqxyMfATql_YUj2cuIqM3HkQPPKmBxfEr_B9DuPGRrulkjdfZuOwAxlKa5e1adI-6txC1aQehr30g4IYl3Y8E/CLNGDBKPKPEEBAHJCKKJFOBAFHNCGMNE_2_3_17_0.crx";
      name = "clngdbkpkpeebahjckkjfobafhncgmne.crx";
      hash = "sha256-b9MDjrRF/hLqWeniszhvZWRdg7bXM32DYVpMw6pOvks=";
    };
    version = "2.3.17";
  }
  {
    id = "cnojnbdhbhnkbcieeekonklommdnndci";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5Ox4VC0l1LC-xFS7oN-H9XL09HSAI4idVlOwaC5BL3pDARmuM0ttMnTzOJPkjfaKsTAbvo1YVjipE4Cg9g8VenawDhFCPew8HSmZwwIN0xjpH2RUojz5pmkM2y8gsAxlKa5a5Vp7Ne1qgQKCqO6cgIrWBBgQZ4/CNOJNBDHBHNKBCIEEEKONKLOMMDNNDCI_8_5_1_0.crx";
      name = "cnojnbdhbhnkbcieeekonklommdnndci.crx";
      hash = "sha256-ksk90bccEtGYzsHSP1ySEaYQ+Ex42iZ3YZylXv8SHYs=";
    };
    version = "8.5.1";
  }
  {
    id = "dneaehbmnbhcippjikoajpoabadpodje";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7vBzd-SBOiJk-AeTrwRo011AcKaI7kPzqRHHQbFtLjnqKw5bdORJ1vu-aqsZ7RZMLlVbIwp3UXQhg0J6C5lRcy-meD-hlfCORqjgfaTP6NV2sAY70GtahXr932kt0AxlKa5Y9xoVGZWYWDwXCrDPgfvpvyoaDz/DNEAEHBMNBHCIPPJIKOAJPOABADPODJE_2_1_0_0.crx";
      name = "dneaehbmnbhcippjikoajpoabadpodje.crx";
      hash = "sha256-MCNsn1HBM/JJrpwxUofMHqpy40SXcV0yJNuFplWAEsg=";
    };
    version = "2.1.0";
  }
  {
    id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7dKpSn7Kn51uxugXQIPZt8sEKHsoK3eCnVoL1CjY1lX6J4NQRxLxdPB4C1JOhD84AhqHp1Iic5DejMQyBIJzfGjeVDCLkqsI3NTcV-vT4vyWG5O-z1MuPdDbhxorkAxlKa5aIX4c0wp55T-Bc2ejz6DUCY4VHG/EIMADPBCBFNMBKOPOOJFEKHNKHDBIEEH_4_9_124_0.crx";
      name = "eimadpbcbfnmbkopoojfekhnkhdbieeh.crx";
      hash = "sha256-+lgx3sG0K4lEvhjidQZNT6DPzXO0zrphaAgQDCtPDw8=";
    };
    version = "4.9.124";
  }
  {
    id = "fmkadmapgofadopljbjfkapdkoienihi";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4RtwggbNThjT0Cyb-wbKftqitDTGeRHQaoDAJVeTzTAXJdMJlEgavY0lHLIq1lTTmoggjgiYXjKJdPz0ss-1O4F6c4aijIT9vrrUPvci58Gjh3I2hJnaEzZzEJkHAAxlKa5eK2Z-P4vnKMic6vHPVvzBP0E2KV/FMKADMAPGOFADOPLJBJFKAPDKOIENIHI_7_0_1_0.crx";
      name = "fmkadmapgofadopljbjfkapdkoienihi.crx";
      hash = "sha256-X3DIlm39NyFz8bGKVjubF8JGeS58EirqeETOBk8Hfgc=";
    };
    version = "7.0.1";
  }
  {
    id = "gcknhkkoolaabfmlnjonogaaifnjlfnp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7HFl384g70hB9avW8AhS5sKp6w9rsXXuV610eaf3OsCiDdopgBVKLSVUCYgXEsSy6BZ89E5kVEI5vA1jpEDz4Xab6pkg1qjM0yGVJhl26h-WKG4yT6-Yxai2-nBskAxlKa5dH5WRrTSeMx75K7mftuqpp_9T68/GCKNHKKOOLAABFMLNJONOGAAIFNJLFNP_9_2_0_0.crx";
      name = "gcknhkkoolaabfmlnjonogaaifnjlfnp.crx";
      hash = "sha256-B0LnrmxNQ3B1iKk89jaIC6Q0k3IP3YEW6yJnW+n4sG4=";
    };
    version = "9.2";
  }
  {
    id = "hipekcciheckooncpjeljhnekcoolahp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7YlZ2N3UYO8meiIPyU_06elBCwNa7jDaJnbiisxPc2hEtKyhs4wYJ7cOj0ugSb7LYo42iymZYpYxIPgHzI7ZxHllfRyHzZs951pWv03rGAarxHAMZSmuW4U5YXXerQ4nPZuTlCvIBhRFWgfA/HIPEKCCIHECKOONCPJELJHNEKCOOLAHP_2_6_0_0.crx";
      name = "hipekcciheckooncpjeljhnekcoolahp.crx";
      hash = "sha256-3a3HVG6dWVRx+EQ48gohNlu3BOzVZrpoZCxnf3chzRY=";
    };
    version = "2.6.0";
  }
  {
    id = "hkgfoiooedgoejojocmhlaklaeopbecg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa6-3zLEPlGIyuYhV6U54pAQo1I293PrFdsZO9Yx9Zn6Vy_FxIj-SPieOxEciRitL3ZtM-g8I9EVAdnV-OE2rwuJDaS08H_DAvVdevflYQu2nMOMTiUvX0PVIg3SmgDGUprl9ja5TT5Kckt34k1AGR9BwP0JCeg/HKGFOIOOEDGOEJOJOCMHLAKLAEOPBECG_1_14_0_0.crx";
      name = "hkgfoiooedgoejojocmhlaklaeopbecg.crx";
      hash = "sha256-NaWNfAH9zyLIVpmK5+cb72PUZ3whU5NwCb+9BA45aGc=";
    };
    version = "1.14";
  }
  {
    id = "hkligngkgcpcolhcnkgccglchdafcnao";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7YEx9cqW_I-8wZvTR56kn_3S1zUJJCxrncdnDkE245BujM3PrnUnB7HLYRFCcJoLWFEq8G_B4vFCCyhYZTU8Vf3nqwU0qR57U3Myt9EwldnzD4vhVQaDoitYnbIekAxlKa5fS1J5pH9AKJEq5jYU1JwJu80XRj/HKLIGNGKGCPCOLHCNKGCCGLCHDAFCNAO_7_3_0_0.crx";
      name = "hkligngkgcpcolhcnkgccglchdafcnao.crx";
      hash = "sha256-g9y4CI1COdmmJxuhYYclmFN7eV0+DBHYkG4nOksPq/o=";
    };
    version = "7.3.0";
  }
  {
    id = "ienfalfjdbdpebioblfackkekamfmbnh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7m6BAUjdmZ5C-jC9gyqhLfdAtVUSiZonUbY7PKUEGHQH4NwDrwTAAxsegeXtS-SyBHOqt5rUdVHEKIbcah-1QHq1UHZqqDsKy8qAqcc4rAPiRecwUGaDmFTra4CZYAxlKa5RDLOT4ylG-C-KVDvueveZFyb0AI/IENFALFJDBDPEBIOBLFACKKEKAMFMBNH_1_14_0_0.crx";
      name = "ienfalfjdbdpebioblfackkekamfmbnh.crx";
      hash = "sha256-rT8K96dq9N9bxtayxFrFvmmUo2zsQ9L7frLw9Lu/7Y4=";
    };
    version = "1.14.0";
  }
  {
    id = "kbmfpngjjgdllneeigpgjifpgocmfgmb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa6wLF8p5y1pOVgvJBV1bnCWRvtM5vGe6vTqDZhobaTsm_cNJH9Vhw6ibQjE2QyzTIf60AxjZNO-mnI5ppWy4fnuormAT9aq-A3ur5dEQrIWst7-FVb6SyX9AZICKovQAMZSmuUGA-R9d-jF8w5xQJyq5GMdgijygQ/KBMFPNGJJGDLLNEEIGPGJIFPGOCMFGMB_5_24_8_0.crx";
      name = "kbmfpngjjgdllneeigpgjifpgocmfgmb.crx";
      hash = "sha256-wM2vceDp5M96hD7aPYEY0c9x1f/fK8Bz1UVokRTJyxg=";
    };
    version = "5.24.8";
  }
  {
    id = "kmcfjchnmmaeeagadbhoofajiopoceel";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa6X5ZLestUsDynOZOtBtLwNCcaVdZ0Y8gPPFVKOAtwC2y0ymbB9ZaS7Xqz0HFVBE0G5cBldoMKuTRyCy48tPRcaNGy72xvoMmaR7mIojoBKIhIL-UfS7cxRilB0jk8AxlKa5QfNgDXliv6FB2vTsOu4k7Aop8tr/KMCFJCHNMMAEEAGADBHOOFAJIOPOCEEL_0_33_5_0.crx";
      name = "kmcfjchnmmaeeagadbhoofajiopoceel.crx";
      hash = "sha256-SaBM++yovHNqOUyurpcvsfotSUzHxgjc8GHvrLOOiGk=";
    };
    version = "0.33.5.0";
  }
  {
    id = "lmhkpmbekcpmknklioeibfkpmmfibljd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7ePMgygX2CT0LNPcPxP4jZJGIDgEJtJofaoBifoBIBipozRPGp7TIbXe64PqfSqyQia67OYvmxcCU1wQ8iNBBBK5-JiEjdHiwGkEAglauN8fEOVK7tTGf7yrbPbKkAxlKa5Ro0G-RCwb4Wt1iLN1hr1bD4Cq4c/LMHKPMBEKCPMKNKLIOEIBFKPMMFIBLJD_3_2_10_0.crx";
      name = "lmhkpmbekcpmknklioeibfkpmmfibljd.crx";
      hash = "sha256-IjNQiQdZSwW8ZDNyUxJTuTBuhs9cpUjltOdwfzR4YKM=";
    };
    version = "3.2.10";
  }
  {
    id = "nhdogjmejiglipccpnnnanhbledajbpd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4meFcGsRDazLOWIq704VaSjxzJCFz1mam_DqGUAxxT9_3CODeC-_lcncoef8o0YmTW9KZUkN-fsvP2dXcQFq872zd3ylJCLNkmoOTTkyubKvQrlLPlBIO8RdMXWCK-AMZSmuWLPfRb3VmfY__V72sbnQoru6lMAw/NHDOGJMEJIGLIPCCPNNNANHBLEDAJBPD_7_7_7_0.crx";
      name = "nhdogjmejiglipccpnnnanhbledajbpd.crx";
      hash = "sha256-v1ZcI/2eLAdO1HFE0FBDNveH5fEFOI9zxihG3ukvASQ=";
    };
    version = "7.7.7";
  }
  {
    id = "nngceckbapebfimnlniiiahkandclblb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7G3dlkzezOtjWwRWHCz7_0LR9jA_Ruee1Uz7_eVFn6gZQ6LMto6Va8JA9UOn9zsKPk4w_xexILVwbOAS9y7FIEkBN_RCuFSdWDRiqB1uh5f1tN80QgF5ELUggVP1XJAMZSmuVO_yMGay7Yt1RFhHfxLrwGRqEYpw/NNGCECKBAPEBFIMNLNIIIAHKANDCLBLB_2026_3_0_0.crx";
      name = "nngceckbapebfimnlniiiahkandclblb.crx";
      hash = "sha256-XOVs2Tvay8hQ13SHz+728BDu2mMyQ0JxUuUI6FZ1NaM=";
    };
    version = "2026.3.0";
  }
  {
    id = "pobhoodpcipjmedfenaigbeloiidbflp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4exikoAOsKW15XzG0rqPjKbm-_pUiWUuCSsWoSRobBvn9qYutpjaYphb1dJ1nK3BQUxxG4Kwi5PrLvBTyZrgreH3IAKwsC716jKRuAR8uNorbl0a-GSkIiqjEOSPwAxlKa5e-rK6yMRcnpVL0C3-AWOOuBeQdQ/POBHOODPCIPJMEDFENAIGBELOIIDBFLP_6_4_1_0.crx";
      name = "pobhoodpcipjmedfenaigbeloiidbflp.crx";
      hash = "sha256-4sMXmTnApAGaK2aEhgp+Cp1vPweS78wRDn9cuYU0+VU=";
    };
    version = "6.4.1";
  }
]
