# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.lists.flatten [
  {
    id = "bhchdcejhohfmigjafbampogmaanbfkg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeo8QMJTAtCQYExzHbdlde3__wzaxs5N55q7XE6f1UN06cNF9kgnRgm9G0ZqBq1K9aA8F7Ofs6j-p4RZVVehBuK0RIwmhEDMUjRznTM2VS6eN_ZqkfoSgXDP0TP0jUoAxlKa5YNue0KLrKGH6dnXwxR30MfB8Eyf/BHCHDCEJHOHFMIGJAFBAMPOGMAANBFKG_0_6_7_0.crx";
      name = "bhchdcejhohfmigjafbampogmaanbfkg.crx";
      hash = "sha256-oKSxB1tJLYHWOEvRFq9+apmWkQ+dZGsng31q/RNoUIg=";
    };
    version = "0.6.7";
  }
  {
    id = "cdglnehniifkbagbbombnjghhcihifij";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeqddHH5JQyCFrkivXXK_p33qgVlSNzoSmVmY_HndReXLwpzJIbJblPLBKUd1HlTkApznsImWpkwTzT2-fbNsPqiup_kDZvbfkgvM6js-LwhDvwO_-KxtJ57NPJuy6MAxlKa5R_RApBxAxB4KLt-WLFsJZ2bhbrl/CDGLNEHNIIFKBAGBBOMBNJGHHCIHIFIJ_1_2_2_5.crx";
      name = "cdglnehniifkbagbbombnjghhcihifij.crx";
      hash = "sha256-weiUUUiZeeIlz/k/d9VDSKNwcQtmAahwSIHt7Frwh7E=";
    };
    version = "1.2.2.5";
  }
  {
    id = "clngdbkpkpeebahjckkjfobafhncgmne";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeonyuHMOWOUJVAfpKzdy1Go-NJ-uD97gSMdH0GURQkkF2fPa3gE3uIR49gZz1ge9y8PNjKY6DnZnPqxTk2e5rdN3oJmlhhAvBZtwwS6oPP5aZ8zUPae5aznbkxVCDUAxlKa5aBkE-ahweS_-Sco3Bg-sl776ZWm/CLNGDBKPKPEEBAHJCKKJFOBAFHNCGMNE_2_3_28_0.crx";
      name = "clngdbkpkpeebahjckkjfobafhncgmne.crx";
      hash = "sha256-2YuNjZcUv7W9sK0RKTcIXjM282263A0KCXXuPBjG8VY=";
    };
    version = "2.3.28";
  }
  {
    id = "cnojnbdhbhnkbcieeekonklommdnndci";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcB_ypD0-t5KKe8MrjOrc0-PUTa6bkIpd9ZknADOwey9fZDjEXQL6VpiMAHj9yJCOGMw4z53oWjOmLNBnXcgM6100MniRU9ZydK1UiikfWU5XgeiuKPmSNWUkwEobVsAxlKa5YYynd5cO_zVTjbagGtnx_2bRRkx/CNOJNBDHBHNKBCIEEEKONKLOMMDNNDCI_8_5_3_0.crx";
      name = "cnojnbdhbhnkbcieeekonklommdnndci.crx";
      hash = "sha256-2MMwrbZKgu1E18VNvJZkk+asA75mwljDYIBDuWRIgq8=";
    };
    version = "8.5.3";
  }
  {
    id = "dneaehbmnbhcippjikoajpoabadpodje";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeq2C8IXempkT0lEj2I8W3V_0Zhn4Twyo0S8N-C-d4j-4Ne4r7JatNkiYUHkkO0juAHleD7fIxtWT4TxwEn9Kc7PVzzAmtnIdh_YWnHprDvFoeArmdi2Yuq3B3p5sAMAxlKa5YhIascHzzpulMbESy1Idcjc3kBv/DNEAEHBMNBHCIPPJIKOAJPOABADPODJE_2_1_0_0.crx";
      name = "dneaehbmnbhcippjikoajpoabadpodje.crx";
      hash = "sha256-MCNsn1HBM/JJrpwxUofMHqpy40SXcV0yJNuFplWAEsg=";
    };
    version = "2.1.0";
  }
  {
    id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoepyfJISdxPzCTQ7_7B4MlfVPvYoFBxqvLaYc2Q6JzQuHJq5PmBls9PBrCug6JAK1jDONPEyPslcceHkliDoLWTAUkb-tudoBG9Jgg4YyR0180u_In_rTY1MQIcK0YgAxlKa5ZdZfJMT5weFIvLdkbrWlXCoifdt/EIMADPBCBFNMBKOPOOJFEKHNKHDBIEEH_4_9_125_0.crx";
      name = "eimadpbcbfnmbkopoojfekhnkhdbieeh.crx";
      hash = "sha256-jAhpgyVucHif6fJ2VUJoOtPAcHUh7BdAEMr9JpdocBY=";
    };
    version = "4.9.125";
  }
  {
    id = "fmkadmapgofadopljbjfkapdkoienihi";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeptaFk-euuGcoXgNVgnm3S8FvuNnCuIkxNDq9DNphrwin8yg58ayd3uUj1xygVvjZTYX5Xjo4AI0bJyJaD26Ui7sea1g73whetrrsITNSJavaNcUFcuBGmP_wGUzS0AxlKa5WsunpW4P-u9_HHwDpkbzWSuF6jn/FMKADMAPGOFADOPLJBJFKAPDKOIENIHI_7_0_1_0.crx";
      name = "fmkadmapgofadopljbjfkapdkoienihi.crx";
      hash = "sha256-X3DIlm39NyFz8bGKVjubF8JGeS58EirqeETOBk8Hfgc=";
    };
    version = "7.0.1";
  }
  {
    id = "gcknhkkoolaabfmlnjonogaaifnjlfnp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeoZmJMuyjOgdk8jp5hfxYR3x02vB1jVM_RYtZvECuruOgjc1c7DDaV3nxfJVr9aiu2h6d9_kzBjoqmQwafcySHygcq7TDw1Do7X5rKnzz4WN2N8Hcxlnb5Pn1JW3W8AxlKa5aSNe-35qaes2ymwMNbwDrhxS5dZ/GCKNHKKOOLAABFMLNJONOGAAIFNJLFNP_9_2_0_0.crx";
      name = "gcknhkkoolaabfmlnjonogaaifnjlfnp.crx";
      hash = "sha256-B0LnrmxNQ3B1iKk89jaIC6Q0k3IP3YEW6yJnW+n4sG4=";
    };
    version = "9.2";
  }
  {
    id = "hipekcciheckooncpjeljhnekcoolahp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoep-rkXn61uG2sNyTPInbMZG0zlVwGSLra5_GJgCV4CZsarm1au155W7tBWRczz2LagMBPNcORFtrlmoWsvtoBDfTfOY117Cf69Qrurt_UP_7cKYAMZSmuVJKfMkh1h08FarMfI_U8KwJKhLbw/HIPEKCCIHECKOONCPJELJHNEKCOOLAHP_2_6_0_0.crx";
      name = "hipekcciheckooncpjeljhnekcoolahp.crx";
      hash = "sha256-3a3HVG6dWVRx+EQ48gohNlu3BOzVZrpoZCxnf3chzRY=";
    };
    version = "2.6.0";
  }
  {
    id = "hkgfoiooedgoejojocmhlaklaeopbecg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoerDGC_APtDTeBAXPI9e8LvUbpSaNDuay_E8XGJaYkuAqR8pN7ysucnJIEpo3k1wwY2KspqboU-X5TEUndBPgTlBiTszyVlGaCT3MQHRtbdH_QQldo6IDg7RwTz07wDGUprlvt1UCY7rT4mb_6H8GkLurQUOkek/HKGFOIOOEDGOEJOJOCMHLAKLAEOPBECG_1_14_0_0.crx";
      name = "hkgfoiooedgoejojocmhlaklaeopbecg.crx";
      hash = "sha256-NaWNfAH9zyLIVpmK5+cb72PUZ3whU5NwCb+9BA45aGc=";
    };
    version = "1.14";
  }
  {
    id = "hkligngkgcpcolhcnkgccglchdafcnao";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoepC9VqNcOKLzhEVUEus_OMzZ17jILmoe5SmiftkATmR3lHg7jzBF-7ok9uKsJ3stSEWE9BQF2_3qgyDz5iKhH-D6H62ivtDs4cY56rd1ioLVOaBIaI7cizdOLI0nDgAxlKa5bY6eR54UfIr7P8ZQtcg_d24ujvW/HKLIGNGKGCPCOLHCNKGCCGLCHDAFCNAO_7_3_1_0.crx";
      name = "hkligngkgcpcolhcnkgccglchdafcnao.crx";
      hash = "sha256-1kE2ZoQ6pOn6usMwZRSuNPZWgT2GQBIGISbNA5lJDGo=";
    };
    version = "7.3.1";
  }
  {
    id = "ienfalfjdbdpebioblfackkekamfmbnh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcACJPUGuw9D9cpD6VAQFWfocj8Cn3YDKxthhwVZf2PkdT7YoNkNwEqQrtRpPxap80UD9BZflOiG1okiOrntPWD3_tB1O79DEg6f1RNvJkyC91X5pmqYS1gjAgS7G7MAxlKa5eyLLIRLD3A_XHCPWds5vP9fPTE6/IENFALFJDBDPEBIOBLFACKKEKAMFMBNH_1_15_1_0.crx";
      name = "ienfalfjdbdpebioblfackkekamfmbnh.crx";
      hash = "sha256-kgwKwaDHC3vPXgMfkX7frfzaIrv1RwNEQqvIKnfbXO4=";
    };
    version = "1.15.1";
  }
  {
    id = "kbmfpngjjgdllneeigpgjifpgocmfgmb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoercMfR8_kirZ8OhcSRqtb-n1eQhOU-_BMm0oL85m8smLMLHghS6uA0lRaczPQCnwUONV0RIZxaV3vE_DbmI0xYabUnh5EiOGdISeZN__V42tVZQM8sHE_nKnkxXngADAMZSmuX-3Lsfbnu_vMFVcIrgqrFCCHxFxw/KBMFPNGJJGDLLNEEIGPGJIFPGOCMFGMB_5_24_8_0.crx";
      name = "kbmfpngjjgdllneeigpgjifpgocmfgmb.crx";
      hash = "sha256-wM2vceDp5M96hD7aPYEY0c9x1f/fK8Bz1UVokRTJyxg=";
    };
    version = "5.24.8";
  }
  {
    id = "kmcfjchnmmaeeagadbhoofajiopoceel";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcDWMFYwPgFcGjlfN_IqGLE1SUnjwQDS1xi3BaCAdX3Kkl_VwlUNeiTFRAB1epipZLC6L4XG3VmhP_qZYnLE2lEkq_2vOQMpyS1iyMXLaFFQBs9S_5NkMWUO2CLP13UAxlKa5Qqk-0WxinbWqyoWlKdCbP-xZa-v/KMCFJCHNMMAEEAGADBHOOFAJIOPOCEEL_0_33_5_0.crx";
      name = "kmcfjchnmmaeeagadbhoofajiopoceel.crx";
      hash = "sha256-SaBM++yovHNqOUyurpcvsfotSUzHxgjc8GHvrLOOiGk=";
    };
    version = "0.33.5.0";
  }
  {
    id = "lmhkpmbekcpmknklioeibfkpmmfibljd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcDI02YvIIiyTwrfe7mTC8cTonmNDqshmSofXk9LEPUGyj9d3BeGxs5LwLHrNcRIxBhG2128SN9qGblZyLbRZSGdsUR2LJqf-3V8VVtlauQYr5Ri9sldthpTp4WZHFcAxlKa5TgcS3ZLwOzemmsOJjaMkXV6Ta1D/LMHKPMBEKCPMKNKLIOEIBFKPMMFIBLJD_3_2_10_0.crx";
      name = "lmhkpmbekcpmknklioeibfkpmmfibljd.crx";
      hash = "sha256-IjNQiQdZSwW8ZDNyUxJTuTBuhs9cpUjltOdwfzR4YKM=";
    };
    version = "3.2.10";
  }
  {
    id = "nhdogjmejiglipccpnnnanhbledajbpd";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcCWE0_1PUmQJ5iVTDc1eE9kZ_XSRIS6L12fn3GXZ5UkWu94lUlw9v8JqMI3DYmo4fwBzVum7m0A1695dgbvRpJif4ePyRntRJJJKwgEj7_CN1X-E5q7TCKibGFi2pozAMZSmuVEbKcHR3-gizBgThwN9a2FaEXC0A/NHDOGJMEJIGLIPCCPNNNANHBLEDAJBPD_7_7_7_0.crx";
      name = "nhdogjmejiglipccpnnnanhbledajbpd.crx";
      hash = "sha256-v1ZcI/2eLAdO1HFE0FBDNveH5fEFOI9zxihG3ukvASQ=";
    };
    version = "7.7.7";
  }
  {
    id = "nngceckbapebfimnlniiiahkandclblb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcDzaxoFB7JIxpMvO1f07Hurc_mzOim0HtG2cq-JiiEbGVnslFheaiFxhPnV_dCdO2ElpeuB443fcj_mKJ4rI4Otmf47hI8e7WBjAC8cOZ6Ide1wGHbRpVWSJjC2umb4AMZSmuWzxT0F5bfIQFzeh-kqaV0IrrkVew/NNGCECKBAPEBFIMNLNIIIAHKANDCLBLB_2026_5_1_0.crx";
      name = "nngceckbapebfimnlniiiahkandclblb.crx";
      hash = "sha256-xRK2iX2ntV6N/PQh/KcK10FoNsKV44B+UtyqvFCvelI=";
    };
    version = "2026.5.1";
  }
  {
    id = "pobhoodpcipjmedfenaigbeloiidbflp";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AXJDbcAhCT94IGETa2Ha1cBFiK1a4cq6sXO697tqC3CekANyyp2vOKB39G2OAxxliX972Bba_br0c4aD9eMKRw-2TY8toTmNsm8jTxoy1UIx-RCmn4VQ386ewDHFC_t0ol8AxlKa5SftlQOALvlSPp46gBQWPU1fxpbX/POBHOODPCIPJMEDFENAIGBELOIIDBFLP_6_4_1_0.crx";
      name = "pobhoodpcipjmedfenaigbeloiidbflp.crx";
      hash = "sha256-4sMXmTnApAGaK2aEhgp+Cp1vPweS78wRDn9cuYU0+VU=";
    };
    version = "6.4.1";
  }
]
