# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  config,
  lib,
  ...
}:
lib.flatten [
  {
    id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7tT_SXuoGz4f73RVoXHiEQT7rm3V98edO5chUe020gbOfwQdzSy7x0Q-05bch0zoG5dRG8jvwGiT94rsXuXUg6BqbEVO7UVYM3nBQMdPwXtfv0kmtPtSSuwgI5F6gEAMZSmuWhjhcMIU5PSS5lMPXUquKEtGCdCg/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_70_0_0.crx";
      name = "cjpalhdlnbpafiamejdnhcphjbkeiagm.crx";
      hash = "sha256-FIbmYVj8cmXce7Vq4h7d2nOjmk4RkCnABmC4y5NDyGk=";
    };
    version = "1.70.0";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa50zVMEoUChMlKfE6oyazajnqWcWVFC98k5OklPE_uC2WPV8u4xuzRlNT7gedRbHM-8P7rBiBHQbcfjANPv0DXgjdPGrwk9SmZ8XzGxY2g4uftija44SRaDV_3DDpAAxlKa5ZOuHZb6hZHkbSoDExB4EHCg2qe6/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_4_4_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-YENhk/gCYlW86L9NCjr0awCObGbPpEStSAKTCnRFBS4=";
    };
    version = "26.4.4";
  }
  {
    id = "jinjaccalgkegednnccohejagnlnfdag";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4dAonJNfXERYMOjSHbsaF6u0kEp0dy5VLs9xmdqnZ_EDBwYCy0-rnElJumRKF4kinDio32hNatUOlO_nl3jJ0ptRDsTun5B-J_6uclNomfkfDL7w8KAOA7-KJ19DcAxlKa5cAzrRaeRbbGS1S5ODd7QKiQUP7A/JINJACCALGKEGEDNNCCOHEJAGNLNFDAG_2_35_0_0.crx";
      name = "jinjaccalgkegednnccohejagnlnfdag.crx";
      hash = "sha256-1CYC+DQm0Glg33AnkuICDyJKvLoCJUKyPPkb7VwCeqs=";
    };
    version = "2.35.0";
  }
  {
    id = "kpaaapnegfaaoimjpagopchdbmenfngl";
    crxPath = pkgs.fetchurl {
      url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx";
      name = "kpaaapnegfaaoimjpagopchdbmenfngl.crx";
      hash = "sha256-X4m1To1n/1zQGrzQPXPyR8KIA4JleyyAh5AjuS2BvYw=";
    };
    version = "10.1.1.0";
  }
  {
    id = "lckanjgmijmafbedllaakclkaicjfmnk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa6Yd7wR2VV7i9FlIFYpPLU_LWpbIUTILCyoJoq2TORt6FYJo10zIbfFLSRSO3K6yxTXZKnNXW6ZSehaeD6y1FtFT_Dh1IsWEqseRbK6g4PuOmK_AMZSmuUoxpGdph3t9B2j5y1-3IMGJCpkvg/LCKANJGMIJMAFBEDLLAAKCLKAICJFMNK_1_26_0_0.crx";
      name = "lckanjgmijmafbedllaakclkaicjfmnk.crx";
      hash = "sha256-rMFzGyrQCJ85p93PDHIy7TU329AZuOjBvuzoeO1Yoxo=";
    };
    version = "1.26.0";
  }
  {
    id = "lkbebcjgcmobigpeffafkodonchffocl";
    crxPath = pkgs.fetchurl {
      url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass-paywalls-chrome-clean-latest.crx&inline=false&commit=ae649d57e4c151af685476e5447a9868c4758bb9";
      name = "lkbebcjgcmobigpeffafkodonchffocl.crx";
      hash = "sha256-3aqQC3Z/ijzN6nQEkYzmc2dvYvc6v23fXdGEXSmvBc4=";
    };
    version = "4.3.4.7";
  }
  {
    id = "lmkeolibdeeglfglnncmfleojmakecjb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7QYMuXsiKpmwhVXyyPw9TwGMgWTJcchjLEE49yXMyiFLH96V_0u_jfNfRXWizApqX96UcENjqnf8SULLUFglY4UFLOu1OcBOftrKaDH0kHtmc6h74ZYU21Bj2pICQAxlKa5ftf0UwDYY03MinoDwh7gWAHX1H1/LMKEOLIBDEEGLFGLNNCMFLEOJMAKECJB_2_22_1_0.crx";
      name = "lmkeolibdeeglfglnncmfleojmakecjb.crx";
      hash = "sha256-am3TSDZeJwFuey7LdrrxGw7ObBRNwaqxNd3crB/G6q0=";
    };
    version = "2.22.1";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7WmsB8SsLHgLWYbOXiZMdNSK_hqrKojmE73rxI-nIYxOmSHtainfVyok24LTWM5Bq94Nn7tBwnsho8VyNfNJgj7v1onms6ChHo5eQQln0x8NFawmEhMrfxrWyvPgYAxlKa5eA7M-mMk9RE8mrjYX0j-oJEt0uv/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_3_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-GvAqrQGXC/uEkm0D167S2TK8gr+ox1af0XB5zK9sxjE=";
    };
    version = "6.1.3";
  }
  (lib.optionals (config.catppuccin.enable) [
    {
      id = "lnjaiaapbakfhlbjenjkhffcdpoompki";
      crxPath = pkgs.fetchurl {
        url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5Qqm3rL32c_mn0gHTPtCwoZe97M0p7ff90YdeKUgBWJvYdHcBxVgEVPeE_MBIvKy7F7MZvuJkdTY2mJxSwrMEIs6MFxSwKYD8de8PFpeAimCqsPGXsqsO-Ow5MmrMAxlKa5c-qlYvr0QIGLMChqIPfnrAnF6EV/LNJAIAAPBAKFHLBJENJKHFFCDPOOMPKI_1_6_1_0.crx";
        name = "lnjaiaapbakfhlbjenjkhffcdpoompki.crx";
        hash = "sha256-ym0nff+4QNPWR6QXDBzpxvAV4dIc8VV5m14uSs19HzU=";
      };
      version = "1.6.1";
    }
  ])
]
