# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  config,
  lib,
  ...
}:
lib.flatten [
  {
    id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7tT_SXuoGz4f73RVoXHiEQT7rm3V98edO5chUe020gbOfwQdzSy7x0Q-05bch0zoG5dRG8jvwGiT94rsXuXUg6BqbEVO7UVYM3nBQMdPwXtfv0kmtPtSSuwgI5F6gEAMZSmuWhjhcMIU5PSS5lMPXUquKEtGCdCg/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_70_0_0.crx";
      name = "cjpalhdlnbpafiamejdnhcphjbkeiagm.crx";
      hash = "sha256-FIbmYVj8cmXce7Vq4h7d2nOjmk4RkCnABmC4y5NDyGk=";
    };
    version = "1.70.0";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5lBBO_qlNvANeBw5GVeQeZ_o1ueV5CsIL0CuVmOrr1dIYEeofoTr5SSVEr6d9QZ4m_C8pvRcc6px7Vqa3quh4BcF3GY_p8Q0B4bCy10GAF7l3aDQ9n-ySyvcGDLT4AxlKa5fF1I1GTovogOJl5rYtdL4-170pu/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_4_20_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-vsqcqdPLqedoczktUgnpmDrQijpjZ0hkV6Ke7ZuCAFE=";
    };
    version = "26.4.20";
  }
  {
    id = "jinjaccalgkegednnccohejagnlnfdag";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7rWYMe78WIriHJvm42BvV2sWvkgOpet3KysEFJilrCssZH37xxRGADR5KPeZvLHdJJ09iNU8eluonzIMwB8SlV-m40HvaqVtn3tCxxyYrf_nLzfWo6GxIUvjaRaUEAxlKa5T-3pjRHJ2cxnrVwCFajMlpKD4E6/JINJACCALGKEGEDNNCCOHEJAGNLNFDAG_2_36_0_0.crx";
      name = "jinjaccalgkegednnccohejagnlnfdag.crx";
      hash = "sha256-OOnRfEig1MO3RuQnGQx2Hr1v3/8XhNN6qUMGdSKc2Ug=";
    };
    version = "2.36.0";
  }
  {
    id = "kpaaapnegfaaoimjpagopchdbmenfngl";
    crxPath = pkgs.fetchurl {
      url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx";
      name = "kpaaapnegfaaoimjpagopchdbmenfngl.crx";
      hash = "sha256-X4m1To1n/1zQGrzQPXPyR8KIA4JleyyAh5AjuS2BvYw=";
    };
    version = "10.1.1.0";
  }
  {
    id = "lckanjgmijmafbedllaakclkaicjfmnk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa6Yd7wR2VV7i9FlIFYpPLU_LWpbIUTILCyoJoq2TORt6FYJo10zIbfFLSRSO3K6yxTXZKnNXW6ZSehaeD6y1FtFT_Dh1IsWEqseRbK6g4PuOmK_AMZSmuUoxpGdph3t9B2j5y1-3IMGJCpkvg/LCKANJGMIJMAFBEDLLAAKCLKAICJFMNK_1_26_0_0.crx";
      name = "lckanjgmijmafbedllaakclkaicjfmnk.crx";
      hash = "sha256-rMFzGyrQCJ85p93PDHIy7TU329AZuOjBvuzoeO1Yoxo=";
    };
    version = "1.26.0";
  }
  {
    id = "lkbebcjgcmobigpeffafkodonchffocl";
    crxPath = pkgs.fetchurl {
      url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass-paywalls-chrome-clean-latest.crx&inline=false&commit=3ce40be62b3a82f421861a47c3d05f6654119249";
      name = "lkbebcjgcmobigpeffafkodonchffocl.crx";
      hash = "sha256-tlLe3/HFWod2OQBqGmp3ScieEz5R+rlkkEoPTopLVtU=";
    };
    version = "4.3.5.3";
  }
  {
    id = "lmkeolibdeeglfglnncmfleojmakecjb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa40dndbG3aW_8A94rye4RKPhtZQ3U6qXvmlB5MFdgRhEKZcrD7JEnD-o2aVNJMSh2XLP1zJSVlndU1GXeyw9bFzKCGO0EYX34SnIoyoxbltCi6eSJVPKZOw5cmfLvwAxlKa5Z3Khb3pCrvRv3aL2ktm_NDuLNaF/LMKEOLIBDEEGLFGLNNCMFLEOJMAKECJB_2_23_0_0.crx";
      name = "lmkeolibdeeglfglnncmfleojmakecjb.crx";
      hash = "sha256-fUfW6KV9iDlZ1fE6Bo0PV4voTZvClpN7yYgIvoM4Y2I=";
    };
    version = "2.23.0";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5TpZKfbc5tWcOacplSWGEJtYVIYr9urvAEIFNSkMyqcDIFcrGUGixKpBZRXYZCdpaXqx4_AxJHf0Ig6rxWS1nf30qTl_8Phn5ZvYjqFeyAoNw0duFYYqcfCINceiQAxlKa5cJZ7vHIZAiHiKP5_8NrjysDNRfb/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_5_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-nE5FE3Eo1jG8sT1KYjVl8JRbmAiyhN8IZObHsAIb0wY=";
    };
    version = "6.1.5";
  }
  (lib.optionals (config.catppuccin.enable) [
    {
      id = "lnjaiaapbakfhlbjenjkhffcdpoompki";
      crxPath = pkgs.fetchurl {
        url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5Qqm3rL32c_mn0gHTPtCwoZe97M0p7ff90YdeKUgBWJvYdHcBxVgEVPeE_MBIvKy7F7MZvuJkdTY2mJxSwrMEIs6MFxSwKYD8de8PFpeAimCqsPGXsqsO-Ow5MmrMAxlKa5c-qlYvr0QIGLMChqIPfnrAnF6EV/LNJAIAAPBAKFHLBJENJKHFFCDPOOMPKI_1_6_1_0.crx";
        name = "lnjaiaapbakfhlbjenjkhffcdpoompki.crx";
        hash = "sha256-ym0nff+4QNPWR6QXDBzpxvAV4dIc8VV5m14uSs19HzU=";
      };
      version = "1.6.1";
    }
  ])
]
