# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  config,
  lib,
  ...
}:
lib.flatten [
  {
    id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7tT_SXuoGz4f73RVoXHiEQT7rm3V98edO5chUe020gbOfwQdzSy7x0Q-05bch0zoG5dRG8jvwGiT94rsXuXUg6BqbEVO7UVYM3nBQMdPwXtfv0kmtPtSSuwgI5F6gEAMZSmuWhjhcMIU5PSS5lMPXUquKEtGCdCg/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_70_0_0.crx";
      name = "cjpalhdlnbpafiamejdnhcphjbkeiagm.crx";
      hash = "sha256-FIbmYVj8cmXce7Vq4h7d2nOjmk4RkCnABmC4y5NDyGk=";
    };
    version = "1.70.0";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5pzXHKc1PEo91XrP1Y1todQtd9ZeuhnZGZMdnPRs9a-g78EyBbcFBXfeHOYp73E8zUUT4SKJVZWEgwzULM914J5CB2UUeazshQYvUTiarG3rh2p0mbvsH01O9VaswAxlKa5Q_FadICPD2KI7LGIcA37EEm0jcS/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_3_3_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-KoluQqhLPmSDWddnAa0eaoRCOpymv/nLJksB5mnXD0w=";
    };
    version = "26.3.3";
  }
  {
    id = "jinjaccalgkegednnccohejagnlnfdag";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4dAonJNfXERYMOjSHbsaF6u0kEp0dy5VLs9xmdqnZ_EDBwYCy0-rnElJumRKF4kinDio32hNatUOlO_nl3jJ0ptRDsTun5B-J_6uclNomfkfDL7w8KAOA7-KJ19DcAxlKa5cAzrRaeRbbGS1S5ODd7QKiQUP7A/JINJACCALGKEGEDNNCCOHEJAGNLNFDAG_2_35_0_0.crx";
      name = "jinjaccalgkegednnccohejagnlnfdag.crx";
      hash = "sha256-1CYC+DQm0Glg33AnkuICDyJKvLoCJUKyPPkb7VwCeqs=";
    };
    version = "2.35.0";
  }
  {
    id = "kpaaapnegfaaoimjpagopchdbmenfngl";
    crxPath = pkgs.fetchurl {
      url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx";
      name = "kpaaapnegfaaoimjpagopchdbmenfngl.crx";
      hash = "sha256-X4m1To1n/1zQGrzQPXPyR8KIA4JleyyAh5AjuS2BvYw=";
    };
    version = "10.1.1.0";
  }
  {
    id = "lckanjgmijmafbedllaakclkaicjfmnk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa6Yd7wR2VV7i9FlIFYpPLU_LWpbIUTILCyoJoq2TORt6FYJo10zIbfFLSRSO3K6yxTXZKnNXW6ZSehaeD6y1FtFT_Dh1IsWEqseRbK6g4PuOmK_AMZSmuUoxpGdph3t9B2j5y1-3IMGJCpkvg/LCKANJGMIJMAFBEDLLAAKCLKAICJFMNK_1_26_0_0.crx";
      name = "lckanjgmijmafbedllaakclkaicjfmnk.crx";
      hash = "sha256-rMFzGyrQCJ85p93PDHIy7TU329AZuOjBvuzoeO1Yoxo=";
    };
    version = "1.26.0";
  }
  {
    id = "lkbebcjgcmobigpeffafkodonchffocl";
    crxPath = pkgs.fetchurl {
      url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass-paywalls-chrome-clean-latest.crx&inline=false&commit=b7126719fdcf74bbd409bbc29a977d0ff3626b73";
      name = "lkbebcjgcmobigpeffafkodonchffocl.crx";
      hash = "sha256-HRflRdBDvuIlhx8GP+g6ryWUvsvteWddLH02qteGV8U=";
    };
    version = "4.3.3.0";
  }
  {
    id = "lmkeolibdeeglfglnncmfleojmakecjb";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa63XA21VIRreJGpNFmwB8KicXYyouDmYTBFBvZZIoww_yt72o97SpcxIvcY70mfj0UIMsbvJNIS6BSXZDM24vL5lehLbVz39QsD935LioH6OKZ_o1Pbzld8vWmEPl4AxlKa5SKE5KOzqyzTNxr2t2Rhd1jiGKbp/LMKEOLIBDEEGLFGLNNCMFLEOJMAKECJB_2_21_4_0.crx";
      name = "lmkeolibdeeglfglnncmfleojmakecjb.crx";
      hash = "sha256-EYvq6VvJWZYdmURBWbcNrA7qlbQApbbmAWhcxjF1XC4=";
    };
    version = "2.21.4";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4y3pOKkq1wcJXMS5148XvBhzM4O2-WwY1WPcjOtpXpXBWWEesAAkA0kZ-48Dsxm-WNxVr1X5HYD-kGG_JTYSN2HNijIANiSJSPY1UaW5nFs4f9kVmtyxrZbDZvfboAxlKa5Q4UGqbCkzf5y5XXJkjjot3CngHg/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_2_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-Nnud/gWl8DVIUa4g4oDYklDZclQRklHl5Uxvh/aEPYQ=";
    };
    version = "6.1.2";
  }
  (lib.optionals (config.catppuccin.enable) [
    {
      id = "lnjaiaapbakfhlbjenjkhffcdpoompki";
      crxPath = pkgs.fetchurl {
        url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa5Qqm3rL32c_mn0gHTPtCwoZe97M0p7ff90YdeKUgBWJvYdHcBxVgEVPeE_MBIvKy7F7MZvuJkdTY2mJxSwrMEIs6MFxSwKYD8de8PFpeAimCqsPGXsqsO-Ow5MmrMAxlKa5c-qlYvr0QIGLMChqIPfnrAnF6EV/LNJAIAAPBAKFHLBJENJKHFFCDPOOMPKI_1_6_1_0.crx";
        name = "lnjaiaapbakfhlbjenjkhffcdpoompki.crx";
        hash = "sha256-ym0nff+4QNPWR6QXDBzpxvAV4dIc8VV5m14uSs19HzU=";
      };
      version = "1.6.1";
    }
  ])
]
